#!/bin/sh
bat(){
	battery="/sys/class/power_supply/BAT0"
	cap=$(cat "${battery}"/capacity)
	stat=$(sed "s/Discharging/🔋/;s/Not charging/🛑/;s/Charging/🔌/;s/Unknown/♻️/;s/Full/⚡/" "$battery"/status)

	[ "$cap" -le 25 ] && [ "$status" = "🔋" ] && warn="❗"

	printf "[ %s%s%s%% ]" "$stat" "$warn" "$cap"
	unset warn
}
