#!/bin/sh
vol(){
	getVolume=$(amixer get Master state | sed -e "s/\[//;s/\]//" | awk '$1=="Front"&&$2=="Left:"{print $5}')
	getState=$(amixer get Master state | awk '$1=="Front"&&$2=="Left:"{print $6}')

	if [ "$getState" = "[off]" ] 
	then 	echo "[ 🔇 ]"
	else	echo "[ 🔈${getVolume} ]"
		fi
	}
